# Generated by Django 2.1.2 on 2018-10-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='localhost', help_text='Server hostname where will be listening.', max_length=64)),
                ('port', models.PositiveIntegerField(default=65265, help_text='Server port where will be listening.')),
                ('running', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='localhost', help_text='Server hostname where this client will connect.', max_length=64)),
                ('port', models.PositiveIntegerField(default=65265, help_text='Server port where this client will connect.')),
                ('resources', models.CharField(help_text='Comma separated resources ids.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Task name', max_length=255)),
                ('payoff', models.PositiveIntegerField(help_text='Task payoff')),
                ('resources', models.CharField(help_text='Comma separated resources ids.', max_length=255)),
            ],
        ),
    ]
