# Generated by Django 2.1.2 on 2018-10-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='name',
            field=models.CharField(default='', help_text='Name for this satellite. It must be unique.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='running',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
