# Generated by Django 2.1.2 on 2018-10-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20181009_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Satellite')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='runner',
            field=models.ManyToManyField(through='simulator.TaskExecution', to='simulator.Satellite'),
        ),
    ]
